CREATE TABLE "type-test_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type-test_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(256),
	"mode" varchar(256),
	"wpm" integer,
	"rawWpm" integer,
	"accuracy" integer,
	"correct" integer,
	"incorrect" integer,
	"extra" integer,
	"missed" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "type-test_game" USING btree ("mode");